/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PitchesRouteImport } from './routes/pitches'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as PitchesCreateRouteImport } from './routes/pitches.create'
import { Route as PitchesIdRouteImport } from './routes/pitches.$id'
import { Route as OnboardingRoleSelectionRouteImport } from './routes/onboarding.role-selection'
import { Route as OnboardingRegistrationRouteImport } from './routes/onboarding.registration'
import { Route as OnboardingInvestorPersonalInfoRouteImport } from './routes/onboarding.investor-personal-info'
import { Route as OnboardingInvestorKycRouteImport } from './routes/onboarding.investor-kyc'
import { Route as OnboardingFounderCompanyInfoRouteImport } from './routes/onboarding.founder-company-info'
import { Route as OnboardingEmailVerificationRouteImport } from './routes/onboarding.email-verification'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as PitchesIdEditRouteImport } from './routes/pitches.$id.edit'
import { Route as PitchesIdAnalyticsRouteImport } from './routes/pitches.$id.analytics'

const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchesRoute = PitchesRouteImport.update({
  id: '/pitches',
  path: '/pitches',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const PitchesCreateRoute = PitchesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => PitchesRoute,
} as any)
const PitchesIdRoute = PitchesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PitchesRoute,
} as any)
const OnboardingRoleSelectionRoute = OnboardingRoleSelectionRouteImport.update({
  id: '/role-selection',
  path: '/role-selection',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingRegistrationRoute = OnboardingRegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingInvestorPersonalInfoRoute =
  OnboardingInvestorPersonalInfoRouteImport.update({
    id: '/investor-personal-info',
    path: '/investor-personal-info',
    getParentRoute: () => OnboardingRoute,
  } as any)
const OnboardingInvestorKycRoute = OnboardingInvestorKycRouteImport.update({
  id: '/investor-kyc',
  path: '/investor-kyc',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingFounderCompanyInfoRoute =
  OnboardingFounderCompanyInfoRouteImport.update({
    id: '/founder-company-info',
    path: '/founder-company-info',
    getParentRoute: () => OnboardingRoute,
  } as any)
const OnboardingEmailVerificationRoute =
  OnboardingEmailVerificationRouteImport.update({
    id: '/email-verification',
    path: '/email-verification',
    getParentRoute: () => OnboardingRoute,
  } as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchesIdEditRoute = PitchesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PitchesIdRoute,
} as any)
const PitchesIdAnalyticsRoute = PitchesIdAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PitchesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pitches': typeof PitchesRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/onboarding/email-verification': typeof OnboardingEmailVerificationRoute
  '/onboarding/founder-company-info': typeof OnboardingFounderCompanyInfoRoute
  '/onboarding/investor-kyc': typeof OnboardingInvestorKycRoute
  '/onboarding/investor-personal-info': typeof OnboardingInvestorPersonalInfoRoute
  '/onboarding/registration': typeof OnboardingRegistrationRoute
  '/onboarding/role-selection': typeof OnboardingRoleSelectionRoute
  '/pitches/$id': typeof PitchesIdRouteWithChildren
  '/pitches/create': typeof PitchesCreateRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/pitches/$id/analytics': typeof PitchesIdAnalyticsRoute
  '/pitches/$id/edit': typeof PitchesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/pitches': typeof PitchesRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/onboarding/email-verification': typeof OnboardingEmailVerificationRoute
  '/onboarding/founder-company-info': typeof OnboardingFounderCompanyInfoRoute
  '/onboarding/investor-kyc': typeof OnboardingInvestorKycRoute
  '/onboarding/investor-personal-info': typeof OnboardingInvestorPersonalInfoRoute
  '/onboarding/registration': typeof OnboardingRegistrationRoute
  '/onboarding/role-selection': typeof OnboardingRoleSelectionRoute
  '/pitches/$id': typeof PitchesIdRouteWithChildren
  '/pitches/create': typeof PitchesCreateRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/pitches/$id/analytics': typeof PitchesIdAnalyticsRoute
  '/pitches/$id/edit': typeof PitchesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pitches': typeof PitchesRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/onboarding/email-verification': typeof OnboardingEmailVerificationRoute
  '/onboarding/founder-company-info': typeof OnboardingFounderCompanyInfoRoute
  '/onboarding/investor-kyc': typeof OnboardingInvestorKycRoute
  '/onboarding/investor-personal-info': typeof OnboardingInvestorPersonalInfoRoute
  '/onboarding/registration': typeof OnboardingRegistrationRoute
  '/onboarding/role-selection': typeof OnboardingRoleSelectionRoute
  '/pitches/$id': typeof PitchesIdRouteWithChildren
  '/pitches/create': typeof PitchesCreateRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/pitches/$id/analytics': typeof PitchesIdAnalyticsRoute
  '/pitches/$id/edit': typeof PitchesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/pitches'
    | '/portfolio'
    | '/auth/login'
    | '/auth/register'
    | '/onboarding/email-verification'
    | '/onboarding/founder-company-info'
    | '/onboarding/investor-kyc'
    | '/onboarding/investor-personal-info'
    | '/onboarding/registration'
    | '/onboarding/role-selection'
    | '/pitches/$id'
    | '/pitches/create'
    | '/onboarding/'
    | '/pitches/$id/analytics'
    | '/pitches/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/pitches'
    | '/portfolio'
    | '/auth/login'
    | '/auth/register'
    | '/onboarding/email-verification'
    | '/onboarding/founder-company-info'
    | '/onboarding/investor-kyc'
    | '/onboarding/investor-personal-info'
    | '/onboarding/registration'
    | '/onboarding/role-selection'
    | '/pitches/$id'
    | '/pitches/create'
    | '/onboarding'
    | '/pitches/$id/analytics'
    | '/pitches/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/pitches'
    | '/portfolio'
    | '/auth/login'
    | '/auth/register'
    | '/onboarding/email-verification'
    | '/onboarding/founder-company-info'
    | '/onboarding/investor-kyc'
    | '/onboarding/investor-personal-info'
    | '/onboarding/registration'
    | '/onboarding/role-selection'
    | '/pitches/$id'
    | '/pitches/create'
    | '/onboarding/'
    | '/pitches/$id/analytics'
    | '/pitches/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PitchesRoute: typeof PitchesRouteWithChildren
  PortfolioRoute: typeof PortfolioRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitches': {
      id: '/pitches'
      path: '/pitches'
      fullPath: '/pitches'
      preLoaderRoute: typeof PitchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/pitches/create': {
      id: '/pitches/create'
      path: '/create'
      fullPath: '/pitches/create'
      preLoaderRoute: typeof PitchesCreateRouteImport
      parentRoute: typeof PitchesRoute
    }
    '/pitches/$id': {
      id: '/pitches/$id'
      path: '/$id'
      fullPath: '/pitches/$id'
      preLoaderRoute: typeof PitchesIdRouteImport
      parentRoute: typeof PitchesRoute
    }
    '/onboarding/role-selection': {
      id: '/onboarding/role-selection'
      path: '/role-selection'
      fullPath: '/onboarding/role-selection'
      preLoaderRoute: typeof OnboardingRoleSelectionRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/registration': {
      id: '/onboarding/registration'
      path: '/registration'
      fullPath: '/onboarding/registration'
      preLoaderRoute: typeof OnboardingRegistrationRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/investor-personal-info': {
      id: '/onboarding/investor-personal-info'
      path: '/investor-personal-info'
      fullPath: '/onboarding/investor-personal-info'
      preLoaderRoute: typeof OnboardingInvestorPersonalInfoRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/investor-kyc': {
      id: '/onboarding/investor-kyc'
      path: '/investor-kyc'
      fullPath: '/onboarding/investor-kyc'
      preLoaderRoute: typeof OnboardingInvestorKycRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/founder-company-info': {
      id: '/onboarding/founder-company-info'
      path: '/founder-company-info'
      fullPath: '/onboarding/founder-company-info'
      preLoaderRoute: typeof OnboardingFounderCompanyInfoRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/email-verification': {
      id: '/onboarding/email-verification'
      path: '/email-verification'
      fullPath: '/onboarding/email-verification'
      preLoaderRoute: typeof OnboardingEmailVerificationRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitches/$id/edit': {
      id: '/pitches/$id/edit'
      path: '/edit'
      fullPath: '/pitches/$id/edit'
      preLoaderRoute: typeof PitchesIdEditRouteImport
      parentRoute: typeof PitchesIdRoute
    }
    '/pitches/$id/analytics': {
      id: '/pitches/$id/analytics'
      path: '/analytics'
      fullPath: '/pitches/$id/analytics'
      preLoaderRoute: typeof PitchesIdAnalyticsRouteImport
      parentRoute: typeof PitchesIdRoute
    }
  }
}

interface OnboardingRouteChildren {
  OnboardingEmailVerificationRoute: typeof OnboardingEmailVerificationRoute
  OnboardingFounderCompanyInfoRoute: typeof OnboardingFounderCompanyInfoRoute
  OnboardingInvestorKycRoute: typeof OnboardingInvestorKycRoute
  OnboardingInvestorPersonalInfoRoute: typeof OnboardingInvestorPersonalInfoRoute
  OnboardingRegistrationRoute: typeof OnboardingRegistrationRoute
  OnboardingRoleSelectionRoute: typeof OnboardingRoleSelectionRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingEmailVerificationRoute: OnboardingEmailVerificationRoute,
  OnboardingFounderCompanyInfoRoute: OnboardingFounderCompanyInfoRoute,
  OnboardingInvestorKycRoute: OnboardingInvestorKycRoute,
  OnboardingInvestorPersonalInfoRoute: OnboardingInvestorPersonalInfoRoute,
  OnboardingRegistrationRoute: OnboardingRegistrationRoute,
  OnboardingRoleSelectionRoute: OnboardingRoleSelectionRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface PitchesIdRouteChildren {
  PitchesIdAnalyticsRoute: typeof PitchesIdAnalyticsRoute
  PitchesIdEditRoute: typeof PitchesIdEditRoute
}

const PitchesIdRouteChildren: PitchesIdRouteChildren = {
  PitchesIdAnalyticsRoute: PitchesIdAnalyticsRoute,
  PitchesIdEditRoute: PitchesIdEditRoute,
}

const PitchesIdRouteWithChildren = PitchesIdRoute._addFileChildren(
  PitchesIdRouteChildren,
)

interface PitchesRouteChildren {
  PitchesIdRoute: typeof PitchesIdRouteWithChildren
  PitchesCreateRoute: typeof PitchesCreateRoute
}

const PitchesRouteChildren: PitchesRouteChildren = {
  PitchesIdRoute: PitchesIdRouteWithChildren,
  PitchesCreateRoute: PitchesCreateRoute,
}

const PitchesRouteWithChildren =
  PitchesRoute._addFileChildren(PitchesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PitchesRoute: PitchesRouteWithChildren,
  PortfolioRoute: PortfolioRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
